name: userity
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  google_fonts: ^3.0.1
  riverpod: ^1.0.3
  hooks_riverpod: ^1.0.4
  go_router: ^4.4.1
  intl: ^0.17.0
  flutter_hooks: ^0.18.5+1
  font_awesome_flutter: ^10.2.1
  persistent_bottom_nav_bar_v2: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
